### ISSUE TITLE
can't connect phone to pc

### ISSUE THREAD

**Issue by usfe25** [MyrikLD/LinusTrinus#27] opened 2021-08-12 19:26 UTC
I installed all the dependencies, downloaded the Trinus VR 2.2.1 app, and tried to follow the stepts in the readme file.
But I did not succeed to connect the phone to the pc, after running `python3 main.py` it displays INFO: discover: Start discover and then nothing happens, the trinus app says usb detected and the start button is purple

**Comment by usfe25** [comment] 2021-09-01 17:27
I managed to make it work on another distro (linux mint)

**Comment by CStafford-14** [comment] 2021-10-01 00:19
Are you using an app called "Trinus VR" or "Trinus CBVR"/"Trinus CBVR Lite"?

**Comment by usfe25** [comment] 2021-10-01 08:08
I'm using Trinus CBVR Lite, sorry I should have been more precise.

**Comment by CStafford-14** [comment] 2021-10-01 10:32
Yep, that's the supported app...

**Comment by cprn** [comment] 2021-11-15 22:15
> I managed to make it work on another distro (linux mint), I was using Pop OS

There should be no difference. Both Linux Mint and Pop!_OS are Ubuntu based. 🤷‍♂️ I'm pretty sure you've done something differently the 2nd time.

**Comment by usfe25** [comment] 2021-11-15 22:45
Yes I know that. I noticed that on a fresh install of Pop OS it works. But it stops working after using the OS for a while.

**Comment by cprn** [comment] 2021-11-16 16:42
Well, connecting your phone to PC is the matter of tethering and not LinusTrinus so I assume you can close this ticket unless it really is something with the server application but in that case we'd need more info. I couldn't reproduce this on my system.

**Closed** 2021-11-17 09:42 UTC
